### ISSUE TITLE
Prettify the researcher-portal GUI

### ISSUE THREAD

**Issue by yuriy-pavlov** [dycons/researcher-portal#18]
As a developer, I desire a pretty and legible UI for the user portals of my application, so that I can improve user engagement and trust.

In order to create a well-designed frontend, the design should be:
1. Spec'd out; contact various stakeholding actors (as well as non-stakeholding experienced individuals) to determine what information should be included in the UI.
2. Drafted roughly, ideally in ~3 different forms.
3. Presented to others for the purpose of collecting feedback.
4. Iterated on, producing a single more-specific and detailed draft.
5. Implemented as code.

Thus this epic will be broken up into multiple stories to be worked on in order.

## Acceptance Criteria
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23

**Comment by sh-ura** [comment]
WON'T DO
Closing due to repo archival.
