### ISSUE TITLE
Implement the pretty Katsu-browser GUI

### ISSUE THREAD

**Issue by yuriy-pavlov** [dycons/researcher-portal#23]
## Acceptance Criteria
- [ ]  Implement the chart designed in #29 using React, React Bootstrap, and highcharts
    - [ ] Try to not introduce dependencies/imports that are not already found in the following `cancogen_dashboard` code: [Individuals Overview](https://github.com/CanDIG/cancogen_dashboard/blob/develop/src/views/IndividualsOverview.js), [Graphs](https://github.com/CanDIG/cancogen_dashboard/tree/develop/src/components/Graphs)
    - [ ] If additional dependencies/imports are introduced, describe them and their purpose in the comments below this ticket
- [ ] Post screenshots of each page in the comments to this ticket, so that the reviewer can refer to them during ticket review.

**Optional:**
- [ ] Implement most of the rest of the final draft of your wireframe for the Katsu browser using React, React Bootstrap, and highcharts

## Resources
The cancogen_dashboard that we installed together two weeks ago contains some example UI for the Katsu individuals endpoint. Try to match its style and dependency list as closely as possible, as the goal is to integrate your UI elements into this dashboard in the long term (ie. after you leave.) According to Jimmy, the package used for the chart components is highcharts
cancogen_dashboard Individuals Overview source code: https://github.com/CanDIG/cancogen_dashboard/blob/develop/src/views/IndividualsOverview.js
cancogen_dashboard charts components source code: https://github.com/CanDIG/cancogen_dashboard/tree/develop/src/components/Graphs

## Time Estimate
The assigner estimates that this story should take ~1 week to complete.

## Where to Cut Corners
Because this will be your final ticket of the term, you may need to make decisions about how to reduce the scope of the ticket until it is something that you can complete before you leave.

Your priorities should be:
1. Receive feedback on your design (this priority has been completed in https://github.com/dycons/researcher-portal/issues/21 )
2. Get experience implementing a data visualizer in React

This means that you should prioritize implementing your own chart from https://github.com/dycons/researcher-portal/issues/29 . Complete this first, then implement as much of the rest of your wireframe as you're able.

Don't worry about Firefox compatibility unless you have time to.
Whatever you don't finish, just document the incomplete components in this ticket, mark the whole ticket as complete, and then focus on celebrating your successes!

**Comment by sh-ura** [comment]
WON'T DO
Closing due to repo archival.
