### ISSUE TITLE
Choose the data and graphing approach that you will take for creating one original chart

### ISSUE THREAD

**Issue by yuriy-pavlov** [dycons/researcher-portal#29]
Charts can be very useful for exploratory analysis of data, as they can visualize trends and relationships in the dataset. Thus charts can stimulate the user to come up with ways to make use of the data.

## Acceptance Criteria
- [x] Figure out what data is useful to graph from either the individuals or phenopackets endpoint, or data from both combined. Think about the data in aggregate, how you can transform it to make useful graphs.
- [x] Decide on what graph you will make to visualize your data of interest. Prioritize intuition; what sort of graph will make the relationships/trends in your data subset easiest to intuitively notice?

## Tips
In this ticket we are trying to facilitate analytics from an exploratory perspective: helping users find trends and relationships in the data that are not immediately visible just from looking at the data in a table.
This approach contrasts other types of analytics, ex. where you receive a question from a researcher and then build charts to answer those questions visually.

## Time Estimate
The assigner estimates that this story should take ~1 day to complete.

**Comment by sh-ura** [comment]
WON'T DO
Closing due to repo archival.
